config/routes.rb
Kfarm::Application.routes.draw do
  get "collection_books/index"
  match 'guide' => "home/guide", :via => :get
  get "faq/index"
  get "home/guide"
  
  resources :books do
    collection do
      get 'search/:q', to: 'books#search'
      get '/:q', to: 'books#index'
    end
    resources :users do
      member do
        post 'collection'
      end
    end
  end
  
  
  resources :jobs do
  end

  resources :users do
    member do
      get 'current_works'
    end
    collection do
      post 'join'
    end
    resources :collection_books, :only => [:index]
  end

  devise_for :users, controllers: { :omniauth_callbacks => "omniauth_callbacks" }
    
  namespace :admin do
    resources :answers
    resources :jobs
    resources :notices
    resources :questions
    resources :reviews
    resources :users
    resources :banners
  end
  
  resources :faq, :only => [:index]
  resources :reviews, :only => [:index, :show, :new, :create]
  resources :notices, :only => [:index, :show]
  resources :answers, :only => [:index, :show]
  resources :questions
  match 'admin' => 'admin/dashboard#index', :via => :get, :as => "admin" 
  root :to => "home#index"
end

app/models/answer.rb
class Answer < ActiveRecord::Base
end

app/models/application.rb
class Application < ActiveRecord::Base
  belongs_to :mentee, class_name: "User"
  belongs_to :job
end

app/models/banner.rb
class Banner < ActiveRecord::Base
  mount_uploader :banner_image, BannerImageUploader
end

app/models/book.rb
class Book < ActiveRecord::Base
  has_one :rental_book
  serialize :authors
  
  include Tire::Model::Search
  include Tire::Model::Callbacks
  
  def self.search(q)
    search = Tire.search 'books' do
      query do
        string q, :default_operator => "AND"
      end
    end
    search.sort{by :published_at, 'desc'}
    
    search.results
  end
  
end

app/models/book_url.rb
class BookUrl < ActiveRecord::Base
end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :mentor, class_name: "User"
  has_many :applications
  has_many :mentees, through: :applications
  
  
end

app/models/notice.rb
class Notice < ActiveRecord::Base
end

app/models/question.rb
class Question < ActiveRecord::Base
end

app/models/rental_book.rb
class RentalBook < ActiveRecord::Base
  belongs_to :host, class_name: "User"
  belongs_to :book
  has_many :rental_applications
  has_many :guest, through: :rental_applications

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
end

app/models/role.rb
class Role < ActiveRecord::Base
  include RoleModel
end

app/models/user.rb
class User < ActiveRecord::Base
  include TheRoleUserModel
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, 
  :validatable, :omniauthable, :omniauth_providers => [:facebook]# , :confirmable 

  has_many :reviews
  
  has_many :works, class_name: "Job", foreign_key: "mentor_id"
  has_many :jobs, through: :applications, foreign_key: "mentee_id"
  has_many :applications, foreign_key: "mentee_id"

  has_many :collection_books, class_name: "RentalBook", foreign_key: "host_id"
  has_many :rental_books, through: :rental_applications, foreign_key: "guest_id"
  has_many :rental_applications, foreign_key: "guest_id"
  
  mount_uploader :avatar, AvatarUploader
  mount_uploader :farm, FarmUploader
  mount_uploader :baby_picture, BabyPictureUploader
  
  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    unless user
      user = User.create!(name:auth.extra.raw_info.name,
                           provider:auth.provider,
                           uid:auth.uid,
                           email:auth.info.email,
                           password:Devise.friendly_token[0,20]
                          )
    end
    user
  end
  
  def current_works
    self.works
  end
end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < ApplicationController
  layout 'admin'
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
    @user = User.all
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to admin_review_path(@review), notice: 'Review was successfully created.' }
        format.json { render action: 'show', status: :created, location: @review }
      else
        format.html { render action: 'new' }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to admin_review_path(@review), notice: 'Review was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to admin_reviews_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:title, :contents, :user_id)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render action: 'show', status: :created, location: @review }
      else
        format.html { render action: 'new' }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:title, :contents)
    end
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/faq_helper.rb
module FaqHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/reviews/_form.html.erb
<%= form_for([:admin, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="row-fluid">
  <!-- block -->
  <div class="block">
      <div class="navbar navbar-inner block-header">
          <div class="muted pull-left">후기 "<%= @review.title %>" 수정</div>
      </div>
      <div class="block-content collapse in">
          <div class="span12">
               <form class="form-horizontal">
                <fieldset>
                  
                  <div class="control-group">
                    <label class="control-label" for="focusedInput">제목</label>
                    <div class="controls">
                      <%= f.text_field :title, id: "focusdInput", class: "input-xlarge focused" %>
                    </div>
                  </div>
                  <div class="control-group">
                    <label class="control-label">내용</label>
                    <div class="controls">
                      <%= f.text_area :contents, id: "focusdInput", class: "input-xlarge focused", style: "width: 600px; height: 200px" %>
                      <span class="help-inline">HTML 사용 가능.</span>
                    </div>
                  </div>
                  <div class="control-group">
                    <label class="control-label">회원 선택</label>
                    <div class="controls">
                      <%= f.collection_select(:user_id, User.all.collect, :id, :email, prompt: "회원 선택") %>
                    </div>
                  </div>


                  <div class="form-actions">
                    <%= f.submit class: "btn btn-primary"  %>
                    <%= link_to "취소", admin_path, class: "btn"%>
                  </div>
                </fieldset>
              </form>

          </div>
      </div>
  </div>
  <!-- /block -->
</div>  
  
<% end %>

app/views/admin/reviews/index.html.erb
 <div class="row-fluid">
  <!-- block -->
  <div class="block">
    <div class="navbar navbar-inner block-header">
        <div class="muted pull-left">후기 전체 목록</div>
    </div>
    <div class="block-content collapse in">
      <div class="span12">
        <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="example">
          <thead>
            <tr>
              <th>#</th>
              <th>제목</th>
              <th>등록일</th>
              <th>관리</th>
            </tr>
          </thead>
          <tbody>
            <% @reviews.each do |review| %>
              <tr class="">
                <td><%= review.id %></td>
                <td><%= review.title %></td>
                <td class="center"><%= review.created_at %></td>
                <td class="center">
                  <%= link_to "상세정보", admin_review_path(review) %>
                  <%= link_to "수정", edit_admin_review_path(review) %>
                  <%= link_to "삭제", admin_review_path(review), method: :delete, confirm: "삭제 OK?" %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <%= link_to "새 리뷰 등록", new_admin_review_path, class: "btn btn-primary"%>
    </div>
  </div>
  <!-- /block -->
</div>

app/views/admin/reviews/show.html.erb
<div class="row-fluid">
    <!-- block -->
    <div class="block">
        <div class="navbar navbar-inner block-header">
            <div class="muted pull-left">후기 "<%= @review.title%>" 정보 보기</div>
        </div>
        <div class="block-content collapse in">
            <div class="span12">
                 <form class="form-horizontal">
                  <fieldset>

                    <div class="control-group">
                      <label class="control-label" for="focusedInput">제목</label>
                      <div class="controls">
                        <span class="input-xlarge uneditable-input">
                          <%= @review.title%>
                        </span>
                      </div>
                    </div>
                    <div class="control-group">
                      <label class="control-label">내용</label>
                      <div class="controls">
                        <span class="input-xlarge uneditable-input"><%= @review.contents %></span>
                      </div>
                    </div>

                    <div class="control-group">
                      <label class="control-label">등록일시</label>
                      <div class="controls">
                        <span class=""><%= @review.created_at %></span>
                      </div>
                    </div>
                    <div class="control-group">
                      <label class="control-label">등록회원정보</label>
                      <div class="controls">
                        <% unless @review.user.nil? %>
                          <span class="">
                            <%= link_to @review.user.email, ademin_user_path(@review.user) %>
                          </span>
                        <% end %>
                      </div>
                    </div>
                    <div class="control-group">
                      <label class="control-label">해당 멘토링</label>
                      <div class="controls">
                        <% unless @review.user.nil? %>
                          <span class="">
                            <%= link_to @review.user.email, ademin_user_path(@review.user) %>
                          </span>
                        <% end %>
                      </div>
                    </div>
                    <div class="form-actions">
                      <%= link_to "목록으로", admin_reviews_path, class: "btn"%>
                      <%= link_to "수정", edit_admin_review_path(@review), class: "btn btn-primary"%>
                    </div>
                  </fieldset>
                </form>
            </div>
        </div>
    </div>
    <!-- /block -->
</div>