config/routes.rb
Kfarm::Application.routes.draw do
  get "collection_books/index"
  match 'guide' => "home/guide", :via => :get
  get "faq/index"
  get "home/guide"
  
  resources :books do
    collection do
      get 'search/:q', to: 'books#search'
      get '/:q', to: 'books#index'
    end
    resources :users do
      member do
        post 'collection'
      end
    end
  end
  
  
  resources :jobs do
  end

  resources :users do
    member do
      get 'current_works'
    end
    collection do
      post 'join'
    end
    resources :collection_books, :only => [:index]
  end

  devise_for :users, controllers: { :omniauth_callbacks => "omniauth_callbacks" }
    
  namespace :admin do
    resources :answers
    resources :jobs
    resources :notices
    resources :questions
    resources :reviews
    resources :users
    resources :banners
  end
  
  resources :faq, :only => [:index]
  resources :reviews, :only => [:index, :show, :new, :create]
  resources :notices, :only => [:index, :show]
  resources :answers, :only => [:index, :show]
  resources :questions
  match 'admin' => 'admin/dashboard#index', :via => :get, :as => "admin" 
  root :to => "home#index"
end

app/models/answer.rb
class Answer < ActiveRecord::Base
end

app/models/application.rb
class Application < ActiveRecord::Base
  belongs_to :mentee, class_name: "User"
  belongs_to :job
end

app/models/banner.rb
class Banner < ActiveRecord::Base
  mount_uploader :banner_image, BannerImageUploader
end

app/models/book.rb
class Book < ActiveRecord::Base
  has_one :rental_book
  serialize :authors
  
  include Tire::Model::Search
  include Tire::Model::Callbacks
  
  def self.search(q)
    search = Tire.search 'books' do
      query do
        string q, :default_operator => "AND"
      end
    end
    search.sort{by :published_at, 'desc'}
    
    search.results
  end
  
end

app/models/book_url.rb
class BookUrl < ActiveRecord::Base
end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :mentor, class_name: "User"
  has_many :applications
  has_many :mentees, through: :applications
  
  
end

app/models/notice.rb
class Notice < ActiveRecord::Base
end

app/models/question.rb
class Question < ActiveRecord::Base
end

app/models/rental_application.rb
class RentalApplication < ActiveRecord::Base
  belongs_to :guest, class_name: "User"
  belongs_to :rental_book
end

app/models/rental_book.rb
class RentalBook < ActiveRecord::Base
  belongs_to :host, class_name: "User"
  belongs_to :book
  has_many :rental_applications
  has_many :guest, through: :rental_applications

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
end

app/models/role.rb
class Role < ActiveRecord::Base
  include RoleModel
end

app/models/user.rb
class User < ActiveRecord::Base
  include TheRoleUserModel
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, 
  :validatable, :omniauthable, :omniauth_providers => [:facebook]# , :confirmable 

  has_many :reviews
  
  has_many :works, class_name: "Job", foreign_key: "mentor_id"
  has_many :jobs, through: :applications, foreign_key: "mentee_id"
  has_many :applications, foreign_key: "mentee_id"

  has_many :collection_books, class_name: "RentalBook", foreign_key: "host_id"
  has_many :rental_books, through: :rental_applications, foreign_key: "guest_id"
  has_many :rental_applications, foreign_key: "guest_id"
  
  mount_uploader :avatar, AvatarUploader
  mount_uploader :farm, FarmUploader
  mount_uploader :baby_picture, BabyPictureUploader
  
  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    unless user
      user = User.create!(name:auth.extra.raw_info.name,
                           provider:auth.provider,
                           uid:auth.uid,
                           email:auth.info.email,
                           password:Devise.friendly_token[0,20]
                          )
    end
    user
  end
  
  def current_works
    self.works
  end
end

app/controllers/admin/jobs_controller.rb
class Admin::JobsController < ApplicationController
  layout 'admin'
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
    @users = User.all
  end

  # GET /jobs/1/edit
  def edit
    @users = User.all
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to admin_job_path(@job), notice: 'Job was successfully created.' }
        format.json { render action: 'show', status: :created, location: @job }
      else
        format.html { render action: 'new' }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to admin_job_path(@job), notice: 'Job was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to admin_jobs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:category, :title, :contents, :started_at, :finished_at, :working_time, :start_time, :finish_time, :learning_time, :level, :workers_count, :pay, :location, :address, :mentor_id, )
    end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @jobs }
    end
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
    @job = Job.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @job }
    end
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render action: 'show', status: :created, location: @job }
      else
        format.html { render action: 'new' }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:category, :title, :content, :time, :level, :workers_count, :pay, :address)
    end
end

app/helpers/admin/jobs_helper.rb
module Admin::JobsHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/faq_helper.rb
module FaqHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/jobs/_form.html.erb
<%= simple_form_for([:admin, @job]) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row-fluid">
  <!-- block -->
  <div class="block">
    <div class="navbar navbar-inner block-header">
        <div class="muted pull-left">멘토링 수정</div>
    </div>
    <div class="block-content collapse in">
      <div class="span12">

          <fieldset>
            <legend>기본정보</legend>
            <div class="control-group">
            <label class="control-label" for="select01">작업명</label>
              <%= f.input(:title, label: false, label_html:{class: "input-xlarge focused", id:"focusedInput"}) %>
            </div>
            <div class="control-group">
              <label class="control-label" for="select01">멘토 선택</label>
              <%= f.collection_select(:mentor_id, User.all.collect, :id, :email, prompt: "멘토 선택") %>
            </div>
            <div class="control-group">
              <label class="control-label" for="select01">종류</label>
              <%= f.input(:category, label: false, input_html:{class: "input-xlarge focused", id:"focusedInput"}) %>
              <div class="controls">
                <!-- <input class="uniform_on" type="radio" name="radio1" id="optionsCheckbox1" value="식량" checked="checked"> <label class="help-inline" for="optionsCheckbox1">식량</label>
                <input class="uniform_on" type="radio" name="radio1" id="optionsCheckbox2" value="채소"> <label class="help-inline" for="optionsCheckbox2">채소</label>
                <input class="uniform_on" type="radio" name="radio1" id="optionsCheckbox3" value="과수"> <label class="help-inline" for="optionsCheckbox3">과수</label>
                <input class="uniform_on" type="radio" name="radio1" id="optionsCheckbox4" value="특용"> <label class="help-inline" for="optionsCheckbox4">특용</label>
                <input class="uniform_on" type="radio" name="radio1" id="optionsCheckbox5" value="기타"> <label class="help-inline" for="optionsCheckbox5">기타</label> -->
              </div>
            </div>
            <div class="control-group">
              <label class="control-label">교육내용</label>
              <div class="controls">
                <%= f.input(:contents, label: false, label_html:{class: "input-xlarge focused", id:"focusedInput"}) %>
              </div>
            </div>
            <div class="control-group">
              <label class="control-label" for="date01">일정</label>
              <div class="controls">
                <%= f.input(:started_at, label: false, label_html:{class: "input focused", id:"focusedInput"}) %>
                ~
                <%= f.input(:finished_at, label: false, label_html:{class: "input focused", id:"focusedInput"}) %>
                <p class="help-block">시작일과 종료일이 같을 수 있습니다.</p>
              </div>
            </div>
            <div class="control-group">
              <label class="control-label">교육시간</label>
              <div class="controls">
                <%= f.input(:working_time, label: false, label_html:{class: "input-xlarge focused", id:"focusedInput"}) %>
                <p class="help-block">시간단위 입력.</p>
              </div>
            </div>
            <div class="control-group">
              <label class="control-label">시작시각</label>
              <div class="controls">
                <%= f.input(:start_time, label: false, label_html:{class: "input-xlarge focused", id:"focusedInput"}) %>
                <p class="help-block">시간단위 입력.</p>
              </div>
            </div>
            <div class="control-group">
              <label class="control-label">종료시각</label>
              <div class="controls">
                <%= f.input(:finish_time, label: false, label_html:{class: "input-xlarge focused", id:"focusedInput"}) %>
                <p class="help-block">시간단위 입력.</p>
              </div>
            </div>
            <div class="control-group">
              <label class="control-label">교육시간</label>
              <div class="controls">
                <%= f.input(:learning_time, label: false, label_html:{class: "input-xlarge focused", id:"focusedInput"}) %>
                <p class="help-block">시간단위 입력.</p>
              </div>
            </div>
            
            <div class="control-group">
              <label class="control-label" for="selectError">난이도</label>
              <div class="controls">
                <%= f.input(:level, label: false, label_html:{class: "input-xlarge focused", id:"focusedInput"}) %>
              </div>
            </div>
            <div class="control-group">
              <label class="control-label" for="focusedInput">필요인원</label>
              <div class="controls">
                <%= f.input(:workers_count, label: false, label_html:{class: "input-xlarge focused", id:"focusedInput"}) %>
                <span class="help-inline">인원수 "명"단위로 표시</span>
              </div>
            </div>
            <div class="control-group">
              <label class="control-label" for="focusedInput">일당</label>
              <div class="controls">
                <%= f.input(:pay, label: false, label_html:{class: "input-xlarge focused", id:"focusedInput"}) %>
                <span class="help-inline">인원당 일당을 "원"단위로 표시</span>
              </div>
            </div>
            <div class="control-group">
              <label class="control-label" for="focusedInput">장소</label>
              <div class="controls">
                <%= f.input(:location, label: false, label_html:{class: "input-xlarge focused", id:"focusedInput"}) %>
                <span class="help-inline">주소나 위치를 알 수 있는 문장이나 단어.</span>
              </div>
            </div>
            <!-- <legend>확장정보</legend>
            <div class="control-group">
              <label class="control-label">멘토링 내용</label>
              <div class="controls">
                <textarea class="input-xlarge textarea" placeholder="Enter text ..." style="width: 810px; height: 200px">우후.. 이런 가르침들이 있다네..</textarea>
                <span class="help-inline">"교육내용"을 구체화해서 기록.</span>
              </div>
            </div>
            <div class="control-group">
              <label class="control-label">지도</label>
              <div class="controls">
                <div id="map" style="width:600px;height:400px;"></div><br />
                lat:<input class="input-xlarge focused" id="mapLat" type="text" value="128.1244"><br />
                lng:<input class="input-xlarge focused" id="mapLng" type="text" value="37.555">
                <span class="help-inline">메인페이지 표시.</span>
              </div>
            </div> -->
            <div class="form-actions">
              <%= f.submit class: "btn btn-primary"  %>
              <%= link_to "취소", admin_jobs_path, class: "btn"%>
            </div>
            <%#= f.input(:address, label_html:{class: "input-xlarge focused", id:"focusedInput"}) %>
            <%#= f.input(:days, label_html:{class: "input-xlarge focused", id:"focusedInput"}) %>
          </fieldset>
      </div>
    </div>
  </div>
  <!-- /block -->  
</div>
<% end %>

app/views/admin/jobs/edit.html.erb
<%= render 'form' %>
<link href="/assets/vendors/datepicker.css" rel="stylesheet" media="screen">
<link href="/assets/vendors/chosen.min.css" rel="stylesheet" media="screen">

<script src="/assets/vendors/jquery-1.9.1.js"></script>
<script src="/assets/bootstrap/js/bootstrap.min.js"></script>
<script src="/assets/vendors/jquery.uniform.min.js"></script>
<script src="/assets/vendors/chosen.jquery.min.js"></script>
<script src="/assets/vendors/bootstrap-datepicker.js"></script>

<script src="/assets/vendors/wysiwyg/wysihtml5-0.3.0.js"></script>
<script src="/assets/vendors/wysiwyg/bootstrap-wysihtml5.js"></script>

<script src="/assets/vendors/wizard/jquery.bootstrap.wizard.min.js"></script>

<!-- <script type="text/javascript" src="http://apis.daum.net/maps/maps3.js?apikey=405db4a3478f2fe559fd2b2d0d27856af183eb07" charset="utf-8"></script> -->
<script type="text/javascript">
	var map;
  var startLat = 37.5374;
  var startLng = 127.004;
	function init() {
    // 지도 출력
		map = new daum.maps.Map(document.getElementById('map'), {
			center: new daum.maps.LatLng(startLat, startLng),
			level: 3
		});
    
    // 마커 출력
		var marker = new daum.maps.Marker({
			position: new daum.maps.LatLng(startLat, startLng)
		});
		marker.setMap(map);
    
    daum.maps.event.addListener(map,"dragend",function(){
      // 좌표값 반환
			var center = map.getCenter();
			document.getElementById("mapLat").value = center.getLat();
      document.getElementById("mapLng").value = center.getLng();
      // 마커 이동
      var position = new daum.maps.LatLng(center.getLat(), center.getLng());
      marker.setPosition(position);
      marker.setMap(map);
    });
    
    daum.maps.event.addListener(map,"click",function(e) {
      // 마커 이동
      marker.setPosition(e.latLng);
      marker.setMap(map);
      // 좌표값 반환
			document.getElementById("mapLat").value = e.latLng.getLat();
      document.getElementById("mapLng").value = e.latLng.getLng();
    });
	}

  $(function() {
    init();
    //$(".datepicker").datepicker();
    //$(".chzn-select").chosen();
  });
</script>

app/views/admin/jobs/index.html.erb
 <div class="row-fluid">
    <!-- block -->
    <div class="block">
        <div class="navbar navbar-inner block-header">
            <div class="muted pull-left">멘토링 목록</div>
        </div>
        <div class="block-content collapse in">
            <div class="span12">
                <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="example">
                <thead>
                  <tr>
                    <th>#</th>
                    <th>멘토</th>
                    <th>종류</th>
                    <th>시작일</th>
                    <th>교육시간</th>
                    <th>난이도</th>
                    <th>필요인원</th>
                    <th>일당</th>
                    <th>관리</th>
                  </tr>
                </thead>
                <tbody>
                  <% @jobs.each do |job| %>
                  <tr class="">
                    <td><%= job.id %></td>
                    <td class="center">
                      <% unless job.mentor.nil? %>
                        <%= link_to job.mentor.email, admin_user_path(job.mentor) %>
                      <% else %>
                        테스트용 데이터
                      <% end %>
                    </td>
                    <td class="center"><%= job.category %></td>
                    <td class="center"><%= job.started_at%></td>
                    <td class="center"><%= job.working_time %></td>
                    <td class="center"><%= job.level %></td>
                    <td class="center"><%= job.workers_count %></td>
                    <td class="center"><%= job.pay %></td>
                    <td class="center">
                      <%= link_to "상세정보", admin_job_path(job) %>
                      <%= link_to "수정", edit_admin_job_path(job) %>
                      <%= link_to "삭제", admin_job_path(job), method: :delete, confirm: "삭제 OK?" %>
                      <a href="#">멘티</a>
                    </td>
                  </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
            <%= link_to "멘토링 프로그램 등록", new_admin_job_path, class: "btn btn-primary"%>
        </div>
    </div>
    <!-- /block -->
</div>

app/views/admin/jobs/new.html.erb
<%= render 'form' %>

<script type="text/javascript">
	var map;
	function init() {
    // 지도 출력
		map = new daum.maps.Map(document.getElementById('map'), {
			center: new daum.maps.LatLng(37.537123, 127.005523),
			level: 3
		});
    
    // 마커 출력
		var marker = new daum.maps.Marker({
			position: new daum.maps.LatLng(37.537123, 127.005523)
		});
		marker.setMap(map);
    
    daum.maps.event.addListener(map,"dragend",function(){
      // 좌표값 반환
			var center = map.getCenter();
			document.getElementById("mapLat").value = center.getLat();
      document.getElementById("mapLng").value = center.getLng();
      // 마커 이동
      var position = new daum.maps.LatLng(center.getLat(), center.getLng());
      marker.setPosition(position);
      marker.setMap(map);
    });
    
    daum.maps.event.addListener(map,"click",function(e) {
      // 마커 이동
      marker.setPosition(e.latLng);
      marker.setMap(map);
      // 좌표값 반환
			document.getElementById("mapLat").value = e.latLng.getLat();
      document.getElementById("mapLng").value = e.latLng.getLng();
    });
	}

  $(function() {
    init();
    //$(".datepicker").datepicker();
    //$(".chzn-select").chosen();
  });
</script>

app/views/admin/jobs/show.html.erb
<div class="row-fluid">
    <!-- block -->
    <div class="block">
        <div class="navbar navbar-inner block-header">
            <div class="muted pull-left">멘토링 정보 보기</div>
        </div>
        <div class="block-content collapse in">
            <div class="span12">
                 <form class="form-horizontal">
                  <fieldset>
                    <legend>기본정보</legend>
                    <div class="control-group">
                      <label class="control-label" for="select01">종류</label>
                      <div class="controls">
                        <span class="input-xlarge uneditable-input"><%= @job.category %></span>
                      </div>
                    </div>
                    <div class="control-group">
                      <label class="control-label">교육내용</label>
                      <div class="controls">
                        <span class="input-xlarge uneditable-input"><%= @job.contents %></span>
                      </div>
                    </div>
                    <div class="control-group">
                      <label class="control-label" for="date01">일정</label>
                      <div class="controls">
                        <span class="input-xlarge uneditable-input"><%= @job.started_at %></span>
                        ~
                        <span class="input-xlarge uneditable-input"><%= @job.finished_at %></span>
                      </div>
                    </div>
                    <div class="control-group">
                      <label class="control-label">교육시간</label>
                      <div class="controls">
                        <span class="input-xlarge uneditable-input"><%= @job.learning_time %></span> 시간
                      </div>
                    </div>
                    <div class="control-group">
                      <label class="control-label">시작시각 ~ 종료시각</label>
                      <div class="controls">
                        <span class="input-xlarge uneditable-input"><%= @job.start_time %></span>시
                        ~
                        <span class="input-xlarge uneditable-input"><%= @job.finish_time %></span>시
                      </div>
                    </div>
                    <div class="control-group">
                      <label class="control-label" for="selectError">난이도</label>
                      <div class="controls">
                        <span class="input-xlarge uneditable-input"><%= @job.level %></span>
                      </div>
                    </div>
                    <div class="control-group">
                      <label class="control-label" for="focusedInput">필요인원</label>
                      <div class="controls">
                        <span class="input-xlarge uneditable-input"><%= @job.workers_count %></span> 명
                      </div>
                    </div>
                    <div class="control-group">
                      <label class="control-label" for="focusedInput">일당</label>
                      <div class="controls">
                        <span class="input-xlarge uneditable-input"><%= @job.pay %></span> 원
                      </div>
                    </div>
                    <div class="control-group">
                      <label class="control-label" for="focusedInput">장소</label>
                      <div class="controls">
                        <span class="input-xlarge uneditable-input"><%= @job.location %></span>
                      </div>
                    </div>
                    
                    <!-- <legend>확장정보</legend>
                    <div class="control-group">
                      <label class="control-label">멘토링 내용</label>
                      <div class="controls">
                        <textarea class="input-xlarge textarea" placeholder="Enter text ..." style="width: 810px; height: 200px" readonly="readonly"></textarea>
                      </div>
                    </div>
                    <div class="control-group">
                      <label class="control-label">지도</label>
                      <div class="controls">
                        <div id="map" style="width:600px;height:400px;"></div>
                      </div>
                    </div> -->

                    <div class="form-actions">
                      <%= link_to "목록으로", admin_jobs_path, class: "btn"%>
                      <%= link_to "수정", edit_admin_job_path(@job), class: "btn btn-primary"%>
                    </div>
                  </fieldset>
                </form>

            </div>
        </div>
    </div>
    <!-- /block -->
</div>

<link href="/assets/vendors/datepicker.css" rel="stylesheet" media="screen">
<link href="/assets/vendors/chosen.min.css" rel="stylesheet" media="screen">

<script src="/assets/vendors/jquery-1.9.1.js"></script>
<script src="/assets/bootstrap/js/bootstrap.min.js"></script>
<script src="/assets/vendors/jquery.uniform.min.js"></script>
<script src="/assets/vendors/chosen.jquery.min.js"></script>
<script src="/assets/vendors/bootstrap-datepicker.js"></script>
<script src="/assets/vendors/wysiwyg/wysihtml5-0.3.0.js"></script>
<script src="/assets/vendors/wysiwyg/bootstrap-wysihtml5.js"></script>
<script src="/assets/vendors/wizard/jquery.bootstrap.wizard.min.js"></script>
<!-- <script type="text/javascript" src="http://apis.daum.net/maps/maps3.js?apikey=405db4a3478f2fe559fd2b2d0d27856af183eb07" charset="utf-8"></script> -->
<script type="text/javascript">
var map;
var startLat = 37.5374;
var startLng = 127.004;
function init() {
// 지도 출력
// map = new daum.maps.Map(document.getElementById('map'), {
// center: new daum.maps.LatLng(startLat, startLng),
// level: 3
// });

// 마커 출력
// var marker = new daum.maps.Marker({
// position: new daum.maps.LatLng(startLat, startLng)
// });
// marker.setMap(map);

}

$(function() {
init();
//$(".datepicker").datepicker();
//$(".chzn-select").chosen();
});
</script>